=== taverna-extras/taverna-plugin-component/taverna-component-repository-api/src/main/resources/ComponentProfile.xsd
<?xml version="1.0"?>
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<xs:schema targetNamespace="http://ns.taverna.org.uk/2012/component/profile"
	elementFormDefault="qualified" xmlns="http://ns.taverna.org.uk/2012/component/profile"
	xmlns:cp="http://ns.taverna.org.uk/2012/component/profile" xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/jaxb http://java.sun.com/xml/ns/jaxb/bindingschema_2_0.xsd"
	jxb:version="2.1">
	<xs:annotation>
		<xs:appinfo>
			<jxb:schemaBindings>
				<jxb:package name="org.apache.taverna.component.api.profile.doc" />
			</jxb:schemaBindings>
		</xs:appinfo>
	</xs:annotation>

	<xs:import namespace="http://www.w3.org/2001/XMLSchema"
		schemaLocation="http://www.w3.org/2001/XMLSchema.xsd" />

	<xs:simpleType name="name">
		<xs:annotation>
			<xs:documentation>A valid name for a port or activity in a Taverna
				workflow.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA_Z0-9_])+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="componentElements">
		<xs:annotation>
			<xs:documentation>
				The component elements that can be annotated.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="InputPort"></xs:enumeration>
			<xs:enumeration value="OutputPort"></xs:enumeration>
			<xs:enumeration value="Activity"></xs:enumeration>
			<xs:enumeration value="Component"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="basicAnnotations">
		<xs:annotation>
			<xs:documentation>
				The basic annotations available in a Taverna
				workflow.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Description"></xs:enumeration>
			<xs:enumeration value="Author"></xs:enumeration>
			<xs:enumeration value="Example"></xs:enumeration>
			<xs:enumeration value="Title"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="componentAnnotations">
		<xs:annotation>
			<xs:documentation>
				Annotations applicable to components.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="basicAnnotations">
			<xs:enumeration value="Description"></xs:enumeration>
			<xs:enumeration value="Author"></xs:enumeration>
			<xs:enumeration value="Title"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="portAnnotations">
		<xs:annotation>
			<xs:documentation>
				Annotations applicable to ports.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="basicAnnotations">
			<xs:enumeration value="Description"></xs:enumeration>
			<xs:enumeration value="Example"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="activityAnnotations">
		<xs:annotation>
			<xs:documentation>
				Annotations applicable to activities.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="basicAnnotations">
			<xs:enumeration value="Description"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="componentAnnotation">
		<xs:simpleContent>
			<xs:extension base="componentAnnotations">
				<xs:attributeGroup ref="xs:occurs" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="portAnnotation">
		<xs:simpleContent>
			<xs:extension base="portAnnotations">
				<xs:attributeGroup ref="xs:occurs" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="activityAnnotation">
		<xs:simpleContent>
			<xs:extension base="activityAnnotations">
				<xs:attributeGroup ref="xs:occurs" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="semanticAnnotation">
		<xs:simpleContent>
			<xs:extension base="xs:anyURI">
				<xs:attribute name="ontology" type="xs:string" use="required" />
				<xs:attribute name="predicate" type="xs:string" use="required" />
				<xs:attribute name="class" type="xs:string" use="optional" />
				<xs:attributeGroup ref="xs:occurs" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="ontology">
		<xs:simpleContent>
			<xs:extension base="xs:anyURI">
				<xs:attribute name="id" type="xs:string" use="required" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="port">
		<xs:sequence>
			<xs:element name="annotation" type="portAnnotation"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="semanticAnnotation" type="semanticAnnotation"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="name" />
		<xs:attribute name="minDepth" type="xs:nonNegativeInteger"
			default="0" />
		<xs:attribute name="maxDepth" type="xs:allNNI" default="unbounded" />
		<xs:attributeGroup ref="xs:occurs" />
	</xs:complexType>

	<xs:complexType name="activity">
		<xs:sequence>
			<xs:element name="annotation" type="activityAnnotation"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="semanticAnnotation" type="semanticAnnotation"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="type" type="xs:string" />
		<xs:attributeGroup ref="xs:occurs" />
	</xs:complexType>
	
	<xs:complexType name="replacement">
	  <xs:complexContent>
		  <xs:restriction base="xs:anyType">
	    	<xs:attribute name="replacementId" type="xs:string" use="required"/>
	    	<xs:attribute name="replacementMessage" type="xs:string" use="required"/>
	    </xs:restriction>
	  </xs:complexContent>
	</xs:complexType>
	
	<xs:simpleType name="pattern">
		<xs:restriction base="xs:string">
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="pruneStack">
	  <xs:complexContent>
		  <xs:restriction base="xs:anyType"/>
	  </xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="handleException">
	  <xs:sequence>
	    <xs:element name="pattern" type="pattern" minOccurs="1" maxOccurs="1"/>
	    <xs:element name="pruneStack" type="pruneStack" minOccurs="0" maxOccurs="1"/>
	    <xs:element name="replacement" type="replacement" minOccurs="0" maxOccurs="1"/>
	  </xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="failLists">
	  <xs:complexContent>
		  <xs:restriction base="xs:anyType"/>
	  </xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="exceptionHandling">
	  <xs:sequence>
	      <xs:element name="failLists" type="failLists" minOccurs="0" maxOccurs="1"/>
	  	<xs:element name="handleException" type="handleException" minOccurs="1" maxOccurs="unbounded"/>
	  </xs:sequence>
	</xs:complexType>

	<xs:complexType name="component">
		<xs:sequence>
			<xs:element name="inputPort" type="port" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="outputPort" type="port" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="activity" type="activity" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="annotation" type="componentAnnotation" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="semanticAnnotation" type="semanticAnnotation" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="exceptionHandling" type="exceptionHandling" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="extends">
	  <xs:attribute name="profileId" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:element name="profile">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:string" />
				<xs:element name="name" type="xs:string" />
				<xs:element name="description" type="xs:string" />
				<xs:element name="extends" type="extends" minOccurs = "0" />
				<xs:element name="ontology" type="ontology" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="component" type="component" >
					<xs:unique name="inputPortUnique">
						<xs:selector xpath="cp:inputPort"></xs:selector>
						<xs:field xpath="@name"></xs:field>
					</xs:unique>
					<xs:unique name="outputPortUnique">
						<xs:selector xpath="cp:outputPort" />
						<xs:field xpath="@name" />
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="ontologyKey">
			<xs:selector xpath="cp:ontology" />
			<xs:field xpath="@id" />
		</xs:key>
		<xs:keyref name="componentKeyRef" refer="ontologyKey">
			<xs:selector xpath="cp:component/cp:semanticAnnotation" />
			<xs:field xpath="@ontology" />
		</xs:keyref>
		<xs:keyref name="inputKeyRef" refer="ontologyKey">
			<xs:selector xpath="cp:component/cp:inputPorts/cp:inputPort/cp:semanticAnnotation" />
			<xs:field xpath="@ontology" />
		</xs:keyref>
		<xs:keyref name="outputKeyRef" refer="ontologyKey">
			<xs:selector xpath="cp:component/cp:outputPorts/cp:outputPort/cp:semanticAnnotation" />
			<xs:field xpath="@ontology" />
		</xs:keyref>
		<xs:keyref name="activityKeyRef" refer="ontologyKey">
			<xs:selector xpath="cp:component/cp:activities/cp:activity/cp:semanticAnnotation" />
			<xs:field xpath="@ontology" />
		</xs:keyref>
	</xs:element>

</xs:schema>

=== taverna-extras/taverna-plugin-component/taverna-component-activity/src/main/resources/BaseProfile.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->

<profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://ns.taverna.org.uk/2012/component/profile"
	xsi:schemaLocation="http://ns.taverna.org.uk/2012/component/profile http://ns.taverna.org.uk/2012/component/profile/ComponentProfile.xsd">

	<id>http://purl.org/wfever/workflow-base-profile</id>
	<name>Workflow base annotation profile</name>
	<description>A base profile for annotating (Taverna) workflows, processes and ports. 
	   This profile is meant to be used as a common base for more specific profiles.
	   The common annotations here are mostly optional (minOccurs=0),
	   covering general annotations like title, contact person, example value.</description>

	<!-- <ontology id="dcterms">http://purl.org/dc/terms/</ontology> The above 
		is flaky.. Instead we use the OWL2 DL object/datatype version from http://bloody-byte.net/rdf/dc_owl2dl/ -->
	<ontology id="dcterms">http://bloody-byte.net/rdf/dc_owl2dl/dcterms_od.owl</ontology>
	<ontology id="foaf">http://xmlns.com/foaf/spec/index.rdf</ontology>
	<ontology id="prov">http://www.w3.org/ns/prov.rdf</ontology>
	<ontology id="pav">http://pav-ontology.googlecode.com/svn/trunk/pav.owl</ontology>
	<ontology id="ro">http://wf4ever.github.com/ro/ro.owl</ontology>
	<ontology id="wfdesc">http://wf4ever.github.com/ro/wfdesc.owl</ontology>
	<ontology id="cito">http://speronitomcat.web.cs.unibo.it:8080/LODE/source?url=http://purl.org/spar/cito</ontology>
	<ontology id="dcat">http://www.w3.org/ns/dcat.rdf</ontology>
	<ontology id="roterms">https://raw.github.com/wf4ever/ro/wfannotations/roterms.owl</ontology>
	<ontology id="skos">http://www.w3.org/TR/skos-reference/skos.rdf</ontology>
	<component>
		<inputPort>
			<semanticAnnotation predicate="http://purl.org/wf4ever/roterms#exampleValue"
				ontology="roterms" minOccurs="0" maxOccurs="unbounded"
				class="http://purl.org/wf4ever/roterms#WorkflowValue" />
			
			<!--  TODO: property chains (?) to say hasArchetype for the typing -->
			<semanticAnnotation predicate="http://purl.org/wf4ever/roterms#ofSemanticType"
				ontology="roterms" minOccurs="0" maxOccurs="unbounded"
				class="http://www.w3.org/2004/02/skos/core#Concept" />
			<semanticAnnotation
				predicate="http://purl.org/wf4ever/roterms#ofStructuralType"
				ontology="roterms" minOccurs="0" maxOccurs="unbounded" />
			<semanticAnnotation predicate="http://purl.org/dc/terms/format"
				ontology="dcterms" minOccurs="0" class="http://purl.org/dc/terms/IMT" />
            <!--  -->
            
            
			<semanticAnnotation predicate="http://purl.org/wf4ever/roterms#defaultValue"
				ontology="roterms" minOccurs="0"
				class="http://purl.org/wf4ever/roterms#WorkflowValue" />
		</inputPort>

        <outputPort>
            <semanticAnnotation predicate="http://purl.org/wf4ever/roterms#exampleValue"
                ontology="roterms" minOccurs="0" maxOccurs="unbounded"
                class="http://purl.org/wf4ever/roterms#WorkflowValue" />
            <semanticAnnotation predicate="http://purl.org/wf4ever/roterms#ofSemanticType"
                ontology="roterms" minOccurs="0" maxOccurs="unbounded"
                class="http://www.w3.org/2004/02/skos/core#Concept" />
            <semanticAnnotation
                predicate="http://purl.org/wf4ever/roterms#ofStructuralType"
                ontology="roterms" minOccurs="0" maxOccurs="unbounded" />

            <semanticAnnotation predicate="http://purl.org/dc/terms/format"
                ontology="dcterms" minOccurs="0" class="http://purl.org/dc/terms/IMT" />            
        </outputPort>
        
		<activity minOccurs="1" maxOccurs="unbounded">
			<semanticAnnotation predicate="http://purl.org/wf4ever/roterms#performsTask"
				ontology="roterms" minOccurs="0" maxOccurs="unbounded"
				class="http://www.w3.org/2004/02/skos/core#Concept" />
			<semanticAnnotation
				predicate="http://purl.org/wf4ever/roterms#requiresSoftware"
				ontology="roterms" minOccurs="0" maxOccurs="unbounded" />
			<semanticAnnotation
				predicate="http://purl.org/wf4ever/roterms#requiresHardware"
				ontology="roterms" minOccurs="0" maxOccurs="unbounded" />
			<semanticAnnotation predicate="http://purl.org/wf4ever/roterms#requireDataset"
				ontology="roterms" minOccurs="0" maxOccurs="unbounded"
				class="http://www.w3.org/ns/dcat#Dataset" />
		</activity>




		<semanticAnnotation predicate="http://purl.org/dc/terms/title"
			ontology="dcterms" minOccurs="0" />
		<semanticAnnotation predicate="http://purl.org/dc/terms/description"
			ontology="dcterms" minOccurs="0" />
		<semanticAnnotation predicate="http://purl.org/dc/terms/created"
			ontology="dcterms" minOccurs="0"
			class="http://www.w3.org/2001/XMLSchema#dateTime" />
		<semanticAnnotation predicate="http://purl.org/dc/terms/modified"
			ontology="dcterms" minOccurs="0"
			class="http://www.w3.org/2001/XMLSchema#dateTime" />
		<semanticAnnotation predicate="http://purl.org/dc/terms/license"
			ontology="dcterms" minOccurs="0"
			class="http://purl.org/dc/terms/LicenseDocument" />
		<semanticAnnotation predicate="http://purl.org/pav/authoredBy"
			ontology="pav" minOccurs="0" maxOccurs="unbounded"
			class="http://xmlns.com/foaf/0.1/Person" />
		<semanticAnnotation predicate="http://purl.org/pav/contributedBy"
			ontology="pav" minOccurs="0" maxOccurs="unbounded"
			class="http://xmlns.com/foaf/0.1/Person" />
		<semanticAnnotation predicate="http://purl.org/wf4ever/roterms#technicalContact"
			ontology="roterms" minOccurs="0" class="http://xmlns.com/foaf/0.1/Agent" />
		<semanticAnnotation predicate="http://purl.org/pav/previousVersion"
			ontology="pav" minOccurs="0" class="http://purl.org/wf4ever/wfdesc#Workflow" />
		<semanticAnnotation predicate="http://purl.org/spar/cito/isDocumentedBy"
			ontology="cito" minOccurs="0" maxOccurs="unbounded" />
		<semanticAnnotation predicate="http://purl.org/dc/terms/audience"
			ontology="dcterms" minOccurs="0" maxOccurs="unbounded"
			class="http://xmlns.com/foaf/0.1/Project" />
		<semanticAnnotation predicate="http://purl.org/dc/terms/identifier"
			ontology="dcterms" minOccurs="1" />
		<semanticAnnotation predicate="http://purl.org/wf4ever/roterms#requiresSoftware"
			ontology="roterms" minOccurs="0" maxOccurs="unbounded" />
		<semanticAnnotation predicate="http://purl.org/wf4ever/roterms#requiresHardware"
			ontology="roterms" minOccurs="0" maxOccurs="unbounded" />
		<semanticAnnotation predicate="http://xmlns.com/foaf/0.1/depiction"
			ontology="foaf" minOccurs="0" class="http://xmlns.com/foaf/0.1/Image" />


	</component>


</profile>

=== taverna-extras/taverna-plugin-component/taverna-component-activity/src/test/resources/ValidationComponent.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->

<profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://ns.taverna.org.uk/2012/component/profile"
	xsi:schemaLocation="http://ns.taverna.org.uk/2012/component/profile http://ns.taverna.org.uk/2012/component/profile/ComponentProfile.xsd">

	<id>eu.scape-project.taverna.component.profile.validation</id>
	<name>Validation Component</name>
	<description>A SCAPE component for validation</description>
	<ontology id="scape">http://www.myexperiment.org/files/864/versions/1/download/SCAPEcomponents.owl</ontology>
	<component>
		<inputPort maxDepth='1'>
			<annotation>Example</annotation>
			<semanticAnnotation ontology="scape"
				predicate="http://scape-project.eu/pc/vocab/profiles#hasPortType"
				class="http://scape-project.eu/pc/vocab/profiles#PortType">
				http://scape-project.eu/pc/vocab/profiles#ObjectURIPort
			</semanticAnnotation>
		</inputPort>
		<inputPort maxDepth='0' minOccurs="2" maxOccurs="unbounded">
			<annotation>Example</annotation>
			<semanticAnnotation ontology="scape"
				predicate="http://scape-project.eu/pc/vocab/profiles#hasPortType"
				class="http://scape-project.eu/pc/vocab/profiles#MeasurePortType" />
			<semanticAnnotation ontology="scape"
				predicate="http://scape-project.eu/pc/vocab/profiles#hasMeasure"
				class="http://scape-project.eu/pc/vocab/profiles#Measure" />
		</inputPort>
		<inputPort maxDepth='0' minOccurs="0" maxOccurs="unbounded">
			<annotation>Example</annotation>
			<semanticAnnotation ontology="scape"
				predicate="http://scape-project.eu/pc/vocab/profiles#hasPortType"
				class="http://scape-project.eu/pc/vocab/profiles#PortType">
				http://scape-project.eu/pc/vocab/profiles#ParameterPort
			</semanticAnnotation>
			<semanticAnnotation ontology="scape"
				predicate="http://scape-project.eu/pc/vocab/profiles#hasParameter"
				class="http://scape-project.eu/pc/vocab/profiles#DefaultParameter"
				maxOccurs="unbounded" />
		</inputPort>
		<outputPort maxDepth='0' minOccurs="1" maxOccurs="unbounded">
			<annotation>Example</annotation>
			<semanticAnnotation ontology="scape"
				predicate="http://scape-project.eu/pc/vocab/profiles#acceptsMeasure"
				class="http://scape-project.eu/pc/vocab/profiles#Measure" />
		</outputPort>
		<activity type="Tool" minOccurs="0" maxOccurs="unbounded">
			<semanticAnnotation ontology="scape"
				predicate="http://scape-project.eu/pc/vocab/profiles#hasDependency"
				class="http://scape-project.eu/pc/vocab/profiles#Dependency"
				maxOccurs="unbounded" />
		</activity>
		<activity minOccurs="0" maxOccurs="unbounded" />
		<annotation>Title</annotation>
		<annotation minOccurs="0">Description</annotation>
		<annotation minOccurs="0">Author</annotation>
		<semanticAnnotation ontology="scape"
			predicate="http://scape-project.eu/pc/vocab/profiles#acceptsMimetype"
			class="http://scape-project.eu/pc/vocab/profiles#AcceptedMimetype"
			maxOccurs="unbounded" />
	</component>
</profile>
